Seccond commit

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -11,13 +11,33 @@ source "${plugin_dir}/lib/utils.bash"
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
 # TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME"
 
 # Download tar.gz file to the download directory
-download_release "$ASDF_INSTALL_VERSION" "$release_file"
+get_arch() {
+    local arch
+    arch=$(uname -m | tr '[:upper:]' '[:lower:]')
+    case ${arch} in
+        x86_64)
+            arch='amd64'
+    esac
+
+    echo "${arch}"
+}
+
+get_platform() {
+    plat=$(uname | tr '[:upper:]' '[:lower:]')
+
+    echo "${plat}"
+}
+
+arch="$(get_arch)"
+platform="$(get_platform)"
+download_release "$ASDF_INSTALL_VERSION" "$release_file" "$arch" "$platform"
 
 #  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+# tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+chmod +x "$release_file"  || fail "Could not extract $release_file"
 
 # Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+# rm "$release_file"
